//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public Manager()
        {
            this.SaleItems = new HashSet<SaleItem>();
        }
    
        public int Id { get; set; }
        public string ManagerName { get; set; }
    
        public virtual ICollection<SaleItem> SaleItems { get; set; }
    }
}
