

//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ModelLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SalesModelContainer : DbContext
{
    public SalesModelContainer()
        : base("name=SalesModelContainer")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Customer> Customers { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<Manager> Managers { get; set; }

    public DbSet<InputFile> InputFiles { get; set; }

    public DbSet<SaleItem> SaleItems { get; set; }

}

}

